services:
  - type: web
    name: cesantoni-experience
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: GOOGLE_API_KEY
        sync: false
      - key: BASE_URL
        sync: false
